### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Rascof**
Try to fix this warning :
`tsid/src/robots/robot-wrapper.cpp: In member function ‘const SE3& tsid::robots::RobotWrapper::position(const Data&, pinocchio::ModelTpl<double>::JointIndex) const’:
tsid/src/robots/robot-wrapper.cpp:171:19: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
       assert(index>=0 && index<data.oMi.size());
              ~~~~~^~~`
...
`tsid/src/robots/robot-wrapper.cpp: In member function ‘void tsid::robots::RobotWrapper::frameJacobianLocal(tsid::robots::RobotWrapper::Data&, pinocchio::ModelTpl<double>::FrameIndex, pinocchio::DataTpl<double>::Matrix6x&) const’:
tsid/src/robots/robot-wrapper.cpp:326:19: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
       assert(index>=0 && index<m_model.frames.size());
              ~~~~~^~~
`

### CODE REVIEW

**Comment by jcarpent** [comment]
Thanks @Rascof for your recent contributions. 
Maybe the best at this stage would be to put all the warning fixes inside a single PR for better tracking and feedback.

**Comment by Rascof** [comment]
Thank you @jcarpent  I will do that from now on ^^

**Comment by Rascof** [comment]
Still some warnings :
`tsid/src/contacts/contact-point.cpp: In member function ‘const Vector& tsid::contacts::ContactPoint::Kp() const’:
tsid/src/contacts/contact-point.cpp:120:76: warning: returning reference to temporary [-Wreturn-local-addr]
 const Vector & ContactPoint::Kp() const { return m_motionTask.Kp().head<3>(); }
                                                                            ^
tsid/src/contacts/contact-point.cpp: In member function ‘const Vector& tsid::contacts::ContactPoint::Kd() const’:
tsid/src/contacts/contact-point.cpp:121:76: warning: returning reference to temporary [-Wreturn-local-addr]
 const Vector & ContactPoint::Kd() const { return m_motionTask.Kd().head<3>(); }
`

**Comment by Rascof** [comment]
Miss click ^^'

**Comment by jcarpent** [comment]
> Still some warnings :
> `tsid/src/contacts/contact-point.cpp: In member function ‘const Vector& tsid::contacts::ContactPoint::Kp() const’: tsid/src/contacts/contact-point.cpp:120:76: warning: returning reference to temporary [-Wreturn-local-addr] const Vector & ContactPoint::Kp() const { return m_motionTask.Kp().head<3>(); } ^ tsid/src/contacts/contact-point.cpp: In member function ‘const Vector& tsid::contacts::ContactPoint::Kd() const’: tsid/src/contacts/contact-point.cpp:121:76: warning: returning reference to temporary [-Wreturn-local-addr] const Vector & ContactPoint::Kd() const { return m_motionTask.Kd().head<3>(); } `

`Kd` should return a Vector3, without const and reference.

**Pull request merged**
