### PR TITLE
Release/1.2.3

### PR DESCRIPTION
**Pull request by nim65s**
Same as stack-of-tasks/dynamic-graph#63 : please don't merge :)

Among other changes:
- use cmake-exports from dependencies
- install cmake-exports for this package
- scripts have been moved to tests/python and used as such
- the python module is now `tsid.so`, instead of
```
tsid/
├── __init__.py
└── libtsid_pywrap.so
```

### CODE REVIEW

**Comment by jcarpent** [comment]
@nim65s Please do not rename the Python package as tsid.so. It won't be compatible with conda for instance.

**Comment by nim65s** [comment]
ok

**Comment by nim65s** [comment]
But I'd really like to understand that better. Do you have any resource for claim ?

**Comment by jcarpent** [comment]
Not really, but this what I had to fix.

**Comment by nim65s** [comment]
Ok, then let's just keep things ugly and hate conda a bit more :)

**Comment by jcarpent** [comment]
I think the issue was for Windows if I remember well. And you cannot do for instance tsid.__file__

**Comment by nim65s** [comment]
Oops, I forgot that, sorry.

**Pull request merged**
