### PR TITLE
Fix #76 as far as the tests are concerned.

### LINKED ISSUE #76: Use https://github.com/stack-of-tasks/eiquadprog
Hi,

@gabrielebndn externalized eiquadprog code into another package, so we should use this one here.

Who wants to handle that ?

If no one is available, I can give a try.

Also, this dependency is LGPL-v3, so this would fix #20

### PR DESCRIPTION
**Pull request by olivier-stasse**
This PR assumes that the PR stack-of-tasks/eiquadprog#8 on Eiquadprog has been accepted.
It removes the eigen quad prog solver that has been externalized by @gabrielebndn
The unit test have been validated.
If someone can check the jupyter notebooks and the examples this could be enough.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
Sorry for previous PR it was against the wrong branch.

**Comment by nim65s** [comment]
You can edit the destination branch instead of close the PR and reopen it :)
I'm marking this PR as draft, as it will have to wait a release of https://github.com/stack-of-tasks/eiquadprog/pull/8

**Comment by olivier-stasse** [comment]
@nim65s Thanks for the tip. I saw that I could change the title, but not the targeted branch.

**Comment by olivier-stasse** [comment]
Dear Andrea could you have a look to https://github.com/stack-of-tasks/eiquadprog/pull/8  ?
The current PR cannot pass if the one on eiquadprog does not pass before, and I think @gabrielebndn is unfortunately not able to do the review.
It should be easy, as the work was done on what you had done in TSID.
Thanks a lot for your help.

**Comment by olivier-stasse** [comment]
Dear @nim65s I merged  stack-of-tasks/eiquadprog#8 so normally this PR can also be merged.
I let you do it according to the policy.

**Comment by nim65s** [comment]
The merge of this PR should wait a release release of eiquadprog. But the release of eiquadprog should wait for me to be able to run the integration tests of sot-talos-balance with it. This currently has other issues : https://github.com/stack-of-tasks/talos_integration_tests/issues/5

**Pull request merged**
